version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8888:80"
        volumes:
            - ./src:/src
            - ./site.conf:/etc/nginx/conf.d/default.conf
    php:
        image: php:fpm
        volumes:
            - ./src:/src